### ISSUE TITLE
Navigation Drawer

### ISSUE THREAD

**Issue by aneesh-neelam** [aneesh-neelam/VITacademics-Android#6]
The Navigation Drawer feels very weird. It is very unlike the ones in the Google Inbox, Gmail, Play Store or Pushbullet apps. 

@karthikb351: I don't know about this, could you help out?

**Comment by gauravagerwala** [comment]
Yes I know. Ill look into it.

**Comment by saurabhsjoshi** [comment]
@aneesh-neelam @gauravagerwala  Google has released new widget for the Drawer View in their support library check here: http://android-developers.blogspot.com/2015/05/android-design-support-library.html

**Comment by aneesh-neelam** [comment]
Perfect! Thanks, @saurabhsjoshi. 

@gauravagerwala, @b0rn2c0de, @CoderHam: Please use the Design Support Library.

**Comment by b0rn2c0de** [comment]
noted. Will look into it

**Comment by b0rn2c0de** [comment]
added proper navigation drawer using design support libraries . Header can be customized as required
